### ISSUE TITLE
HLA does not handle enable/disable frames

### ISSUE THREAD

**Issue by Marcus10110** [timkostka/saleae_sdmmc_from_spi#1]
First thing, nice work! 

I just spoke with another user who was having a problem with this HLA.

The problem is that we (Saleae) introduced some changes to the SPI analyzer, and added new frame types to represent transitions on the enable signal, so HLAs can tell when a packet starts.

You may have been developing without using the enable input of the SPI analyzer, in which case none of these frames would be generated.

SPI Analyzer frame type documentation:
https://support.saleae.com/extensions/analyzer-frame-types/spi-analyzer

The simplest solution might be to check if the frame type is "result" at the top of the decode function, and return if the frame type is anything else.
https://github.com/timkostka/saleae_sdmmc_from_spi/blob/62836f96ecf7751b9c5e4b197eb11a098bd5a25b/sdmmc_from_spi.py#L372

**Comment by timkostka** [comment]
Thanks!

Yes, this was developed during the first iteration of HLAs and I had to
modify it when Logic 2.x was updated the first time.

I’ll take another look and update again to work with the current version of
Logic 2.

Stay tuned.

**Comment by timkostka** [comment]
I loaded Logic v2.3.5 and this HLA seems to work just fine.

The SPI used to feed data into this HAL shouldn't have a SPI enable line, as there is no such line in the SDMMC protocol.  Setting the SPI enable pin to anything other than "None" would not make sense here.

Am I missing something?

**Comment by timkostka** [comment]
Closing this, as the SPI enable line should be set to "None" for this HLA per the instructions.

Note that some SD cards can be controlled in "SPI mode".  In that mode, commands and responses are sent on different lines.  This is not the correct HLA for that.  This is for SD mode in which both the controller and the sd card can control the CMD line.
